import { Inter } from "next/font/google";
import "./globals.css";
import "react-toastify/dist/ReactToastify.css";
import CustomNavbar from "@/components/CustomNavbar";
import { ToastContainer } from "react-toastify";
import StoreProvider from "./StoreProvider";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://cdn-uicons.flaticon.com/2.3.0/uicons-bold-rounded/css/uicons-bold-rounded.css"
        />
        <link
          rel="stylesheet"
          href="https://cdn-uicons.flaticon.com/2.3.0/uicons-brands/css/uicons-brands.css"
        ></link>
      </head>
      <body className={inter.className}>
        <StoreProvider>
          <CustomNavbar />
          <div>
            <div>
              {/* <FixedCart/> */}
              {/* <CartComponent/> */}
              <ToastContainer />
            </div>
            <div>{children}</div>
          </div>
        </StoreProvider>
      <Footer />
      </body>
    </html>
  );
}
